"""``teaf`` — la única API pública de TORUS Enterprise Application Framework.

Desde este Sprint (2.5.1, Public SDK & Packaging), un consumidor externo de
TEAF nunca importa ``teaf._internal.*`` directamente — solo ``from teaf import ...``.
``teaf/_internal/`` (``core``, ``config``, ``runtime``, ``sdk``, ``contracts``,
``providers``, ``modules``, ...) es la implementación privada detrás de
esta fachada; puede reorganizarse internamente entre Sprints sin romper a
ningún consumidor de ``teaf`` mientras el contrato de este archivo se
mantenga (ver docs/public-api/VERSIONING.md, ``PUBLIC_API_VERSION``).

Cada símbolo exportado aquí vive, en realidad, en una fachada especializada
bajo ``teaf/`` (``application.py``, ``runtime.py``, ``modules.py``,
``services.py``, ``events.py``, ``configuration.py``, ``capabilities.py``,
``health.py``, ``version.py``) — ver docs/public-api/PACKAGE-STRUCTURE.md
para qué vive en cada una. Este archivo solo agrega, nunca implementa.

Superficie pública: los catorce símbolos pedidos explícitamente
(``Application``, ``Runtime``, ``Module``, ``ModuleBase``, ``ModuleBuilder``,
``ModuleContext``, ``ModuleManifest``, ``ServiceContainer``, ``EventBus``,
``CapabilityRegistry``, ``ModuleRegistry``, ``Health``, ``Configuration``,
``Version``) más un puñado de enums/dataclasses *compañeros*, sin los
cuales los símbolos principales no se podrían usar en la práctica sin
recurrir a ``teaf._internal.*`` (``ModuleCategory``/``CapabilityCategory`` para
categorizar; ``Lifetime`` para declarar el ciclo de vida de un servicio;
``Event`` para publicar en el ``EventBus``; ``get_configuration`` como
función homóloga de ``Configuration``). Nada más se exporta — no hay
importaciones implícitas ni reexportaciones accidentales de símbolos
internos.

Desde Sprint 2.7 (Enterprise Security Platform, ADR-007) se reexporta,
además, todo lo declarado en ``teaf.security`` (``teaf/security.py``) — el
mismo criterio: ``from teaf import SecurityContext`` funciona igual que
``from teaf.security import SecurityContext``, exactamente como ya ocurre
con ``teaf.modules``/``teaf.runtime``/etc. ``SecurityModule`` no se expone
(ni aquí ni en ``teaf.security``) — mismo criterio que ``DatabaseModule``
(ver docs/public-api/PUBLIC-API.md, sección 6): ningún módulo real del
framework se expone desde ``teaf/``, se construye la seguridad de una
aplicación componiendo estas piezas directamente.

Desde Sprint 2.8 (Enterprise Observability Platform, ADR-008) se reexporta,
con el mismo criterio, todo lo declarado en ``teaf.observability``
(``teaf/observability.py``) — ``ObservabilityModule`` tampoco se expone
(mismo motivo que ``SecurityModule``/``DatabaseModule``).

Desde Sprint 2.9 (Enterprise API Protection Platform, ADR-009) se reexporta
igualmente todo lo declarado en ``teaf.api`` (``teaf/api.py``). Con **una
excepción a la regla anterior**, deliberada y documentada: ``ApiProtectionModule``
sí se expone, a diferencia de los otros tres módulos reales. La protección
de APIs se activa como una unidad —ocho subsistemas con configuración,
orden de middlewares y ciclo de vida compartidos—, así que obligar a
recomponerla pieza a pieza en cada aplicación sería repetición sin ganancia
de desacoplamiento; componer a mano sigue siendo posible con el resto de
``teaf.api``. Ver ``teaf/api.py`` y docs/public-api/PUBLIC-API.md, sección 6.
"""

from __future__ import annotations

from teaf.api import (
    DEFAULT_IDEMPOTENT_METHODS,
    MIDDLEWARE_ORDER,
    ApiAudit,
    ApiAuditMiddleware,
    ApiAuditRecord,
    ApiGateway,
    ApiOutcome,
    ApiProtectionConfiguration,
    ApiProtectionException,
    ApiProtectionModule,
    ApiProtectionPolicy,
    ApiRequestContext,
    ApiVersion,
    ApiVersioningPolicy,
    ApiVersionMiddleware,
    ApiVersionNegotiator,
    AuditSink,
    BrotliCompressionProvider,
    CompressionAlgorithm,
    CompressionMiddleware,
    CompressionNegotiator,
    CompressionPolicy,
    CompressionProvider,
    CorsMiddleware,
    CorsPolicy,
    FixedWindowAlgorithm,
    GatewayDecision,
    GzipCompressionProvider,
    IdempotencyConflictException,
    IdempotencyManager,
    IdempotencyMiddleware,
    IdempotencyRecord,
    IdempotencyStore,
    InMemoryAuditSink,
    InMemoryIdempotencyStore,
    InMemoryQuotaStore,
    InMemoryRateLimitStore,
    InvalidRequestException,
    LeakyBucketAlgorithm,
    LoggingAuditSink,
    ProtectionScope,
    QuotaDecision,
    QuotaExceededException,
    QuotaKind,
    QuotaManager,
    QuotaMiddleware,
    QuotaPeriod,
    QuotaRule,
    QuotaStore,
    QuotaUsage,
    RateLimitAlgorithm,
    RateLimitAlgorithmBase,
    RateLimitDecision,
    RateLimiter,
    RateLimitExceededException,
    RateLimitMiddleware,
    RateLimitRule,
    RateLimitState,
    RateLimitStore,
    RedisIdempotencyStore,
    RedisQuotaStore,
    RedisRateLimitStore,
    RequestTooLargeException,
    RequestValidationMiddleware,
    RequestValidationPolicy,
    RequestValidator,
    ResponseTooLargeException,
    SlidingWindowAlgorithm,
    TokenBucketAlgorithm,
    UnsupportedApiVersionException,
    UnsupportedContentTypeException,
    VersioningStrategy,
    VersionNegotiation,
    build_audit_record,
    build_fingerprint,
    build_request_context,
    get_algorithm,
    parse_accept_encoding,
)
from teaf.application import Application
from teaf.cache import (
    CacheBackend,
    CacheConfiguration,
    CacheModule,
    CacheProvider,
    InMemoryCacheProvider,
    RedisCacheConfiguration,
    RedisCacheProvider,
)
from teaf.capabilities import CapabilityCategory, CapabilityRegistry
from teaf.configuration import Configuration, get_configuration
from teaf.events import Event, EventBus
from teaf.health import Health
from teaf.modules import (
    Module,
    ModuleBase,
    ModuleBuilder,
    ModuleCategory,
    ModuleContext,
    ModuleManifest,
    ModuleRegistry,
)
from teaf.observability import (
    AzureMonitorExporter,
    CompositeHealthChecker,
    ConsoleExporter,
    Counter,
    DatadogExporter,
    DiagnosticReport,
    DynatraceExporter,
    ElasticExporter,
    Exporter,
    Gauge,
    GrafanaExporter,
    HealthCheck,
    HealthReport,
    HealthStatus,
    Histogram,
    JaegerExporter,
    Meter,
    NewRelicExporter,
    ObservabilityMiddleware,
    OtelCounter,
    OtelGauge,
    OtelHistogram,
    OtelMeter,
    OtelSpan,
    OtelTracer,
    OtelUpDownCounter,
    OtlpExporter,
    PreparedExporter,
    PrometheusExporter,
    Span,
    SpanKind,
    SpanStatus,
    SplunkExporter,
    TelemetryContext,
    TelemetryProvider,
    TraceContext,
    Tracer,
    UpDownCounter,
    ZipkinExporter,
    build_diagnostic_report,
    get_logger,
    get_telemetry_context,
    set_telemetry_context,
)
from teaf.runtime import Runtime
from teaf.security import (
    ANONYMOUS_IDENTITY,
    ANONYMOUS_PRINCIPAL,
    AnonymousIdentityProvider,
    ApiKeyIdentityProvider,
    ApiKeyProvider,
    ApiKeyRecord,
    ApiKeyStore,
    Argon2PasswordHasher,
    AuthenticationCredentials,
    AuthenticationProvider,
    AuthenticationResult,
    AuthorizationProvider,
    AzureADProvider,
    BcryptPasswordHasher,
    Claims,
    CryptoProvider,
    DefaultPolicyEvaluator,
    HmacCryptoProvider,
    Identity,
    IdentityProvider,
    IdentityProviderRegistry,
    InMemoryApiKeyStore,
    InMemoryTokenRevocationStore,
    JWTIdentityProvider,
    JWTProvider,
    LDAPProvider,
    OAuth2IdentityProvider,
    OpenIDConnectProvider,
    PasswordHasher,
    Permission,
    PermissionResolver,
    Policy,
    PolicyEvaluator,
    PolicyRule,
    Principal,
    PrincipalResolver,
    Role,
    RolePermissionResolver,
    RoleResolver,
    SAMLIdentityProvider,
    SecurityContext,
    SecurityMiddleware,
    StaticRoleResolver,
    TokenPair,
    TokenProvider,
    TokenRevocationStore,
    allow_anonymous,
    authorize,
    current_claims,
    current_identity,
    current_principal,
    current_security_context,
)
from teaf.services import Lifetime, ServiceContainer
from teaf.version import CURRENT_VERSION as Version

__all__ = [
    # -- Los catorce símbolos pedidos explícitamente (Sprint 2.5.1, sección 2).
    "Application",
    "Runtime",
    "Module",
    "ModuleBase",
    "ModuleBuilder",
    "ModuleContext",
    "ModuleManifest",
    "ServiceContainer",
    "EventBus",
    "CapabilityRegistry",
    "ModuleRegistry",
    "Health",
    "Configuration",
    "Version",
    # -- Compañeros imprescindibles para usar los símbolos de arriba sin
    # -- tocar ``teaf._internal.*`` — ver docstring del módulo.
    "CapabilityCategory",
    "Event",
    "Lifetime",
    "ModuleCategory",
    "get_configuration",
    # -- Plataforma de seguridad empresarial (Sprint 2.7, ADR-007) — ver
    # -- ``teaf/security.py`` para el detalle y la justificación de cada nombre.
    "ANONYMOUS_IDENTITY",
    "ANONYMOUS_PRINCIPAL",
    "AnonymousIdentityProvider",
    "ApiKeyIdentityProvider",
    "ApiKeyProvider",
    "ApiKeyRecord",
    "ApiKeyStore",
    "Argon2PasswordHasher",
    "AuthenticationCredentials",
    "AuthenticationProvider",
    "AuthenticationResult",
    "AuthorizationProvider",
    "AzureADProvider",
    "BcryptPasswordHasher",
    "Claims",
    "CryptoProvider",
    "DefaultPolicyEvaluator",
    "HmacCryptoProvider",
    "Identity",
    "IdentityProvider",
    "IdentityProviderRegistry",
    "InMemoryApiKeyStore",
    "InMemoryTokenRevocationStore",
    "JWTIdentityProvider",
    "JWTProvider",
    "LDAPProvider",
    "OAuth2IdentityProvider",
    "OpenIDConnectProvider",
    "PasswordHasher",
    "Permission",
    "PermissionResolver",
    "Policy",
    "PolicyEvaluator",
    "PolicyRule",
    "Principal",
    "PrincipalResolver",
    "Role",
    "RolePermissionResolver",
    "RoleResolver",
    "SAMLIdentityProvider",
    "SecurityContext",
    "SecurityMiddleware",
    "StaticRoleResolver",
    "TokenPair",
    "TokenProvider",
    "TokenRevocationStore",
    "allow_anonymous",
    "authorize",
    "current_claims",
    "current_identity",
    "current_principal",
    "current_security_context",
    # -- Plataforma de observabilidad empresarial (Sprint 2.8, ADR-008) — ver
    # -- ``teaf/observability.py`` para el detalle y la justificación de cada nombre.
    "AzureMonitorExporter",
    "CompositeHealthChecker",
    "ConsoleExporter",
    "Counter",
    "DatadogExporter",
    "DiagnosticReport",
    "DynatraceExporter",
    "ElasticExporter",
    "Exporter",
    "Gauge",
    "GrafanaExporter",
    "HealthCheck",
    "HealthReport",
    "HealthStatus",
    "Histogram",
    "JaegerExporter",
    "Meter",
    "NewRelicExporter",
    "ObservabilityMiddleware",
    "OtelCounter",
    "OtelGauge",
    "OtelHistogram",
    "OtelMeter",
    "OtelSpan",
    "OtelTracer",
    "OtelUpDownCounter",
    "OtlpExporter",
    "PreparedExporter",
    "PrometheusExporter",
    "Span",
    "SpanKind",
    "SpanStatus",
    "SplunkExporter",
    "TelemetryContext",
    "TelemetryProvider",
    "TraceContext",
    "Tracer",
    "UpDownCounter",
    "ZipkinExporter",
    "build_diagnostic_report",
    "get_logger",
    "get_telemetry_context",
    "set_telemetry_context",
    # -- Plataforma de protección de APIs (Sprint 2.9, ADR-009) — ver
    # -- ``teaf/api.py`` para el detalle y la justificación de cada nombre.
    "ApiAudit",
    "ApiAuditMiddleware",
    "ApiAuditRecord",
    "ApiGateway",
    "ApiOutcome",
    "ApiProtectionConfiguration",
    "ApiProtectionException",
    "ApiProtectionModule",
    "ApiProtectionPolicy",
    "ApiRequestContext",
    "ApiVersion",
    "ApiVersionMiddleware",
    "ApiVersionNegotiator",
    "ApiVersioningPolicy",
    "AuditSink",
    "BrotliCompressionProvider",
    "CompressionAlgorithm",
    "CompressionMiddleware",
    "CompressionNegotiator",
    "CompressionPolicy",
    "CompressionProvider",
    "CorsMiddleware",
    "CorsPolicy",
    "DEFAULT_IDEMPOTENT_METHODS",
    "FixedWindowAlgorithm",
    "GatewayDecision",
    "GzipCompressionProvider",
    "IdempotencyConflictException",
    "IdempotencyManager",
    "IdempotencyMiddleware",
    "IdempotencyRecord",
    "IdempotencyStore",
    "InMemoryAuditSink",
    "InMemoryIdempotencyStore",
    "InMemoryQuotaStore",
    "InMemoryRateLimitStore",
    "InvalidRequestException",
    "LeakyBucketAlgorithm",
    "LoggingAuditSink",
    "MIDDLEWARE_ORDER",
    "ProtectionScope",
    "QuotaDecision",
    "QuotaExceededException",
    "QuotaKind",
    "QuotaManager",
    "QuotaMiddleware",
    "QuotaPeriod",
    "QuotaRule",
    "QuotaStore",
    "QuotaUsage",
    "RateLimitAlgorithm",
    "RateLimitAlgorithmBase",
    "RateLimitDecision",
    "RateLimitExceededException",
    "RateLimitMiddleware",
    "RateLimitRule",
    "RateLimitState",
    "RateLimitStore",
    "RateLimiter",
    "RedisIdempotencyStore",
    "RedisQuotaStore",
    "RedisRateLimitStore",
    "RequestTooLargeException",
    "RequestValidationMiddleware",
    "RequestValidationPolicy",
    "RequestValidator",
    "ResponseTooLargeException",
    "SlidingWindowAlgorithm",
    "TokenBucketAlgorithm",
    "UnsupportedApiVersionException",
    "UnsupportedContentTypeException",
    "VersionNegotiation",
    "VersioningStrategy",
    "build_audit_record",
    "build_fingerprint",
    "build_request_context",
    "get_algorithm",
    "parse_accept_encoding",
    # -- Caché distribuida (Sprint 3.0, ADR-012) — ver ``teaf/cache.py`` para
    # -- por qué se exporta el módulo y no solo el contrato.
    "CacheBackend",
    "CacheConfiguration",
    "CacheModule",
    "CacheProvider",
    "InMemoryCacheProvider",
    "RedisCacheConfiguration",
    "RedisCacheProvider",
]
